#!/bin/bash
# Distinguish between linux and mac to determine which build script to run.
DIR="$( cd "$( dirname "$0" )" && pwd )"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    $DIR/linux_build;
elif [[ "$OSTYPE" == "darwin"* ]]; then
    $DIR/mac_build;
fi

