#!/bin/bash
boot2docker init &> /dev/null
boot2docker up &> /dev/null
$(boot2docker shellinit)
if ! [ -f id_rsa.pub ]; then
    ssh-keygen -b 1024 -t rsa -f id_rsa -P ""
fi
docker build -t 3bem-dev .
