#!/bin/bash
# Distinguish between linux and mac to determine which start script to run.
DIR="$( cd "$( dirname "$0" )" && pwd )"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    $DIR/linux_start;
elif [[ "$OSTYPE" == "darwin"* ]]; then
    $DIR/mac_start;
fi

